### ISSUE TITLE
How to keep space between barcode lines or how to make the barcode line thin?

### ISSUE THREAD

**Issue by tashi-179** [toretore/barby#109]
While printing barcodes using the TSC TTP-244 Pro printer, the barcode is blooded and coming too close and at some point in time, the barcode gets overlapped by another line. Ultimately barcode scanner is not able to scan the barcode.

Anybody have any idea how we can get a clean barcode, which can print in any kind of printer?

Below is my code

```ruby
require 'barby/barcode/code_128'
require 'barby/outputter/svg_outputter'

Barby::Code128B.new(code).to_svg(height: 20, margin: 1, xdim: 1)
```

**Comment by tashi-179** [comment]
@toretore why did you close this issue? Do you have any valid solution for it?

**Comment by toretore** [comment]
This is not a support forum.

https://groups.google.com/g/ruby-barby
