### ISSUE TITLE
NoMethodError Exception: undefined method `background_color=' for Barby::RmagickOutputter

### ISSUE THREAD

**Issue by mrudult** [toretore/barby#114]
`background_color` [here](https://github.com/toretore/barby/blob/master/lib/barby/outputter/rmagick_outputter.rb#L56)  should be `background` instead.

**Comment by boutil** [comment]
This issue has been reported in Debian too, and the corresponding patch applied.
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1054752

**Comment by toretore** [comment]
Fixed in #113
