### ISSUE TITLE
Pdf417 barcode is not getting scanned

### ISSUE THREAD

**Issue by Piyushchandra1987** [toretore/barby#47]
I am generating a pdf417 barcode using below code. It is getting generated properly but i am not able to scan it. i am using prawn for generating pdf

`barcode = Barby::Pdf417.new("Test Data")`
`barcode.annotate_pdf(@pdf, {:height => 25.mm, :xdim => 1.2, :x => 8.mm, :y => @pdf.cursor - 25.mm})`

**Comment by toretore** [comment]
Going to need more than that.

**Comment by Piyushchandra1987** [comment]
Hi @toretore 

Here is sample program I am using 
https://github.com/Piyushchandra1987/Pdf417Barcode/blob/master/BarbyPdf417.rb
 
you can check generated barcode at https://github.com/Piyushchandra1987/Pdf417Barcode/blob/master/Screen%20Shot%202015-06-04%20at%2014.45.22.png

OS : Mac OS X Yoesmite 10.10.3
Jruby version : jruby 1.7.4 (1.9.3p392) 2013-05-16 2390d3b on Java HotSpot(TM) 64-Bit Server VM 1.8.0_25-b17 +indy [darwin-x86_64]
Java Version: java version "1.8.0_25"

for verifying I am using this site http://www.datasymbol.com/barcode-recognition-sdk/barcode-reader/online-barcode-decoder.html

and  Barcode scanners by manatee Works on my android phone (https://play.google.com/store/apps/details?id=com.manateeworks.barcodescanners&hl=en)
