### ISSUE TITLE
Screen scanners do not read Code39

### ISSUE THREAD

**Issue by rlogic** [toretore/barby#51]
First of all thanks for creating barby library. We use it quite often. However we've encountered a problem using it.

Screen scanners like Motorola MC9190 don't read barby-generated Code 39 barcodes. It didn't matter what outputter we used. We've checked PNG, GIF, PDF, etc. and it worked 1 time for every 10 attempts. We had to switch some JS library and it is working perfect.

Maybe it's the problem with lines thickness that does not appears on printed barcodes.

**Comment by toretore** [comment]
If it is a problem with thickness then you should change the values in the outputter to see if it makes any difference. I'm closing this as it doesn't have any usable information for understanding if there is a problem and what it might be.
