### ISSUE TITLE
Support for GS1 SSCC barcodes

### ISSUE THREAD

**Issue by JanC89** [toretore/barby#53]
I can see that you support [GS1-128](https://github.com/toretore/barby/blob/master/lib/barby/barcode/gs1_128.rb) barcodes. 

Would it be to specialized/"high level" to support [Serial Shipping Container Code (SSCC-18)](http://www.gs1.org/serial-shipping-container-code-sscc)

Something like:
```ruby
GS1_SSCC.new(data, application_identifier, extension_digit, company_prefix)
```

It would then automatically calculate the check digit and set the subset type to C

Example:
```ruby
GS1_SSCC.new('000113256', '00', '3', '5712852')
```
would produce `00357128520001132567` - where 7 is the check digit calculated.

**Comment by toretore** [comment]
I've recently deprecated explicit support for GS1-128; everyone should use Code128 directly instead, also for this type.
