### ISSUE TITLE
Invalid barcode output with EAN13/UPC

### ISSUE THREAD

**Issue by jheathco** [toretore/barby#54]
I'm generating a barcode for an EAN13/UPC and it doesn't seem to be working properly:

```
barcode = Barby::EAN13.new('091037788863')
img#barcode src="data:image/svg+xml;base64,#{Base64.encode64(barcode.to_svg(margin: 0))}"
```

When I scan the resulting barcode, it's taking off the initial 0 and adding a trailing 0, resulting in 910377888630.  What gives?

**Comment by toretore** [comment]
0 is the check digit for this number. If your scanner is UPC-specific it will probably discard the first 0; try changing the number, scanning it and comparing with the check digit (`barcode.checksum`) and see if it is the case.

**Comment by jheathco** [comment]
It appears that certain applications scan it correctly, others don't.  However, the resulting barcode is different than the one I received pre-generated from the company I purchased the UPC from.  Do you know why that might be?

**Comment by toretore** [comment]
Can you show the pregeneratrd one?

**Comment by jheathco** [comment]
Sure.

http://drop.johnheathco.com/ryAjV

Here is the one Barby is generating:

http://drop.johnheathco.com/tT4hy

**Comment by toretore** [comment]
The initial 0 is part of the number, not a UPC designator. This should generate the correct version:

    Barby::EAN13.new('009103795804')

or

    Barby::UPCA.new('09103795804')

**Comment by jheathco** [comment]
This still isn't working with the changes.  Scanners are still picking up an extra number (091037958044) and the generated image looks different.
