### ISSUE TITLE
uninitialized constant Barby::CairoOutputter

### ISSUE THREAD

**Issue by rvgarimrj** [toretore/barby#58]
Hi. I have rails 4.1 and ruby 2.1 installed. Installed gem barby and could not make it work. The require cairo gives me an error that could not load such file. And if I remove the require, gives me the error uninitialized constant Barby::CairoOutputter

Can anyone help me with this ?

**Comment by toretore** [comment]
I don't understand what this means so I'm closing it. Reopen with more information if you want.
