### ISSUE TITLE
EAN13 does not accept EAN13 codes (ArgumentError: data not valid)

### ISSUE THREAD

**Issue by 341bms** [toretore/barby#60]
I'm not able do generate any of my valid EAN13 codes (e.g. 4050486102473, 4050486086735, 5707471006665, 5998309302206)

```
require 'barby' 
require 'barby/barcode/ean_13' 
Barby::EAN13.new("4050486102473") 
ArgumentError: data not valid
```

Any ideas?
Thanks in advance!

**Comment by toretore** [comment]
Remove the check digit
