### ISSUE TITLE
Barcode does not print numbers below barcode

### ISSUE THREAD

**Issue by RichardGrossman** [toretore/barby#77]
`
APPLICATION CONTROLLER

class ApplicationController < ActionController::Base
  require 'chunky_png'
  require 'barby'
  require 'barby/barcode/ean_13'
  require 'barby/outputter/png_outputter'
  
  def barcode_output(barstring)
    barcode_string = barstring.to_s.rjust(12,"0")
    barcode        = Barby::EAN13.new(barcode_string)
  
    # PNG OUTPUT
    data           = barcode.to_image(height: 40, margin: 10).to_data_url
  end
end

ACTION
class ClientsController < ApplicationController

  def clientlist
    @clients = Client.all
    @barcode = barcode_output('1234567')
    respond_to do |format|
      format.html
      format.pdf do
        render pdf:          "clientlist",
               template:     'clients/clientlist.html.erb',
               show_as_html: params[:debug].present?,
               locals:       { :clients => @clients },
               outline:      { outline:       true,
                               outline_depth: 50 },
               margin:       { top:    10, # default 10 (mm)
                               bottom: 10,
                               left:   10,
                               right:  10 }
      end
    end
  end

CLIENTLIST.HTML.ERB

<div class="row" style="width:100%; margin-left: 0px; margin-right:20px">
  <span class="col-lg-8 dataheader">Clients</span>
  <span class="col-lg-1">BARCODE</span>
  <span class="col-lg-1">
  </span>
</div>
<div>
  <br>
  <br>
  <br>
  "<%= wicked_pdf_image_tag_for_public(@barcode) %>
  <br>
  <br>
</div>

`

**Comment by RichardGrossman** [comment]
![screen shot 2017-04-02 at 9 22 28 pm](https://cloud.githubusercontent.com/assets/1606071/24595349/8f6e7b14-17ea-11e7-955f-571f86303c91.png)

**Comment by RichardGrossman** [comment]
I found a similar question back in 2009 that said barby won't print the barcode text.

Now I just have to get rid of those two '' to the left of the image...

**Comment by toretore** [comment]
It's not supposed to.

**Comment by RichardGrossman** [comment]
I saw that in a questuion, from 2009 but I wondered if that changed.  
I can print the number below the barcode but there's no way I can interleave the leading 0 off to the left and the number to the right.


Any idea of where the two  small extraneous lines are coming from at the bottom left? (  '' )
