### ISSUE TITLE
Add MaxiCode

### ISSUE THREAD

**Issue by jtreitz** [toretore/barby#81]
Any chance to see this project support MaxiCode?

Would be happy to fund it.

**Comment by toretore** [comment]
MaxiCode doesn't currently fit the format required to work with Barby, and would require some big structural changes.

**Comment by jtreitz** [comment]
okay
thanks for the reply though

**Comment by toretore** [comment]
I'm not opposed to it though, I'm just saying that it would be a lot of work and I myself won't have time to do it.

**Comment by jtreitz** [comment]
We are again considering adding this symbology to Barby. Based on your statement that it be "a lot of work" I assume you already have an idea how this could/should be approached? Could you give a an indication how you'd want to see this implemented?
