### ISSUE TITLE
Adding barcode value below the image

### ISSUE THREAD

**Issue by engpeter2010** [toretore/barby#82]
The library is great and very helpful. If you can add an option to include the barcode value below the image, it will be much better and flexible. Thank you.

**Comment by toretore** [comment]
This has been asked many times before, and it's still not part of the plan to include this. You can easily add this to an image yourself.

**Comment by mikebaldry** [comment]
I wrote an outputter that generates nicer looking EAN-13 images https://gist.github.com/mikebaldry/ff58c7f881e716bbfe096840faf06d36

It doesn't size perfectly, but looks good with `{margin: 10, xdim: 2, font_size: 22}`. YMMV
