### ISSUE TITLE
[Question] Version 0.6.1

### ISSUE THREAD

**Issue by JapSeyz** [toretore/barby#99]
Hi,

First of all, thanks for the stellar library!

In our Gemfile.lock we're using version 0.6.1, which seems to have been pulled from the tags & releases here, along with 0.6.2. Should we upgrade, is there a reason 0.6.1 is no longer available?

Cheers,
Jesper

**Comment by toretore** [comment]
I'm not sure what happened to the tag, but there's no reason to not use
0.6.1

**Comment by JapSeyz** [comment]
Okay great, thanks for the swift response.
